name: Deploy Statamic Static Site to GitHub Pages

on:
  push:
    branches: [main]  # or 'master' if that's your default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, bcmath, intl, gd

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate static site
        run: php please ssg:generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storage/app/static
          publish_branch: main
